// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddiqxqbjcjuibzgyjzqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkaXF4cWJqY2p1aWJ6Z3lqenFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTUxOTMsImV4cCI6MjA2NDE3MTE5M30.IPk4McpcQhFMELc4zwiWy_MIiiAA2Zb9TYS-iHmTQ2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);